import cookie from 'cookie';

import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useIntl } from 'react-intl';
import { Layout } from '@components';
import { getSessionCookie } from '@utils/cookies';
import { translation } from '@utils/translation';
import { UserSession } from '@utils/types';

const Home = ({ session }: { session: UserSession }) => {
  console.log('LOG::  ~ session', session);
  const intl = useIntl();
  const i18n = translation.home(intl);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>{i18n.title}</h1>
      </Layout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  try {
    const cookies = cookie.parse(req.headers.cookie || '');
    const session: UserSession = await getSessionCookie(cookies);
    console.log('LOG::  ~ session', session);

    /**
     * Fetch Items from cart
     */
    const resCart = await fetch(
      `${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/jsonapi/carts`,
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          Authorization:
            session.token.token_type + ' ' + session.token.access_token,
        },
      }
    );
    const data = await resCart.json();
    console.log('LOG::  ~ data', data);
    /**
     * Search for all
     */

    // const products = await getResourceCollectionFromContext(
    //   "product--video",
    //   context,
    //   {
    //     params: {
    //       sort: "-created",
    //       include: 'variations,stores',
    //     },
    //   }
    // )
    // console.log('LOG::  ~ products', products[0])

    // const res = await fetch(`${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/jsonapi/products/video`)
    // const data = await res.json()
    // console.log('LOG::  ~ data', data)

    /**
     * Add items to cart
     */
    // const cartToken = window.localStorage.getItem('cartToken') || Math.random().toString(36).substring(2)
    // const res = await fetch(
    //   `${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/jsonapi/cart/add?include=order_id,order_id.order_items`,
    //   {
    //     method: 'POST',
    //     headers: {
    //       'Content-Type': 'application/vnd.api+json',
    //       'Commerce-Cart-Token': `ABC-123`,
    //       'Commerce-Current-Store': `98106e1f-ca58-42b1-a25f-8ac20c13847a`,
    //     },
    //     body: JSON.stringify({
    //       data: [
    //         {
    //           type: 'product-variation--video',
    //           id: '57af6be9-14a5-4267-858d-a86b7dc2cb58',
    //           meta: {
    //             quantity: 1,
    //             combine: true,
    //           },
    //         },
    //       ],
    //     }),
    //   }
    // );
    // const data = await res.json();
    // console.log('LOG::  ~ data', data);

    // const node = await getResource<DrupalNode>(
    //   'node--article',
    //   '5d5da489-ffb5-49c7-88b6-f147664bca4a'
    // );

    return {
      props: { session },
    };
  } catch {
    return {
      props: {},
    };
  }
};

export default Home;
