import Head from 'next/head';

import { useIntl } from 'react-intl';

import { translation } from '@utils/translation';

const Cart = () => {
  const intl = useIntl();
  const i18n = translation.home(intl);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{i18n.title}</h1>
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores,
        officia eligendi perspiciatis corporis minus debitis eius doloribus
        placeat dolor alias cupiditate mollitia obcaecati consectetur odit dicta
        cumque blanditiis corrupti deserunt! Nostrum nulla eius doloremque
        facere sunt iusto, animi aut eum perferendis quibusdam excepturi
        deleniti quae vel expedita perspiciatis aliquam commodi esse nemo, modi,
        at asperiores ut explicabo magnam! Voluptatibus, assumenda! Nobis minima
        dolor, ipsam consectetur praesentium quam ad non! Obcaecati voluptatem
        perferendis harum expedita eaque tempora aperiam, fugiat adipisci
        laudantium, facere, illum officia. Omnis explicabo ad quas quos laborum
        quam. Nostrum perspiciatis labore adipisci magnam, tenetur iste nobis
        eaque neque distinctio in dolore ullam odit voluptatum modi odio
        provident excepturi. Blanditiis quis magnam repudiandae, sint obcaecati
        temporibus odio vero enim? Quasi ratione vero officiis eum omnis
        explicabo similique obcaecati fugit esse officia maxime est, mollitia
        cupiditate id ea accusantium beatae ducimus facere totam rem! Odio
        aliquam nemo soluta ipsum asperiores. Impedit, cupiditate ipsam quidem
        molestiae officia dolore tempora id rem repellendus ullam velit sed
        aspernatur voluptatibus accusantium accusamus corporis culpa et sequi
        voluptas cum aliquid fugit! Hic modi assumenda et. Officiis assumenda
        aliquam perspiciatis tempora, et soluta. Corrupti, similique consequatur
        eaque illum repellat consequuntur laborum recusandae deserunt labore
        beatae inventore sequi ipsum quod ducimus nisi necessitatibus, cum
        dolore praesentium quae. Commodi similique ipsam et doloremque dolor
        ratione neque aspernatur quidem, adipisci voluptas, quo accusamus
        pariatur dolorem quam quisquam quae consequatur, ducimus assumenda non!
        Distinctio, repudiandae! Quo qui sunt nostrum magnam! Optio et
        perspiciatis temporibus tempora aut est eum minus quasi quidem fuga nemo
        deleniti, possimus enim, ipsam blanditiis veniam unde molestiae sed ipsa
        cupiditate necessitatibus a perferendis? Velit, deserunt ratione.
        Facilis, repudiandae autem? Possimus ullam obcaecati dignissimos non
        tempora? Quas sapiente eveniet error velit fugit. Cumque qui fugit non
        dolorem laudantium dignissimos at hic. Illum molestiae nostrum aut odio
        autem. Ullam quasi alias libero veniam debitis repudiandae. Ad, laborum?
        Eaque adipisci quasi aspernatur rem magni consequuntur, aliquid iste
        natus aliquam quibusdam hic repellendus mollitia unde ab error tenetur
        cum voluptates? Dolor voluptatem rerum eum! Illum perspiciatis est
        tempora, veniam quam vero voluptate, sapiente consequuntur modi, facere
        alias. Velit, id cum sit consequatur veniam tempora veritatis
        praesentium eaque dolore! Omnis, cupiditate! Sunt qui ullam, sequi quis,
        reiciendis aperiam perferendis molestiae ratione deleniti facere at quae
        doloremque. Deserunt, esse voluptatibus. Aliquid totam, ipsum omnis at
        tempore dicta. Officia repellendus dicta nisi quo. Soluta, laborum quo.
        Fugiat doloremque expedita sequi illum recusandae nobis incidunt
        voluptates esse, blanditiis quia accusantium earum debitis aperiam
        officiis ratione! Corporis tempore possimus amet asperiores labore
        laboriosam fuga at. Vel, tempore. Delectus deserunt enim totam dolore
        hic ipsa perspiciatis quia culpa maiores. Facilis mollitia eligendi
        rerum temporibus velit, sunt doloribus voluptates iste veniam quisquam
        officia rem fugit exercitationem assumenda?
      </p>
    </div>
  );
};

// export const getServerSideProps: GetServerSideProps = async ({ req }) => {
//   try {
//     const cookies = cookie.parse(req.headers.cookie || '');
//     const session: UserSession = await getSessionCookie(cookies);
//     console.log('LOG::  ~ session', session);

//     /**
//      * Fetch Items from cart
//      */
//     const resCart = await fetch(
//       `${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/jsonapi/carts`,
//       {
//         headers: {
//           'Content-Type': 'application/x-www-form-urlencoded',
//           Authorization:
//             session.token.token_type + ' ' + session.token.access_token,
//         },
//       }
//     );
//     const data = await resCart.json();
//     console.log('LOG::  ~ data', data);
/**
 * Search for all
 */

// const products = await getResourceCollectionFromContext(
//   "product--video",
//   context,
//   {
//     params: {
//       sort: "-created",
//       include: 'variations,stores',
//     },
//   }
// )
// console.log('LOG::  ~ products', products[0])

// const res = await fetch(`${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/jsonapi/products/video`)
// const data = await res.json()
// console.log('LOG::  ~ data', data)

/**
 * Add items to cart
 */
// const cartToken = window.localStorage.getItem('cartToken') || Math.random().toString(36).substring(2)
// const res = await fetch(
//   `${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}/jsonapi/cart/add?include=order_id,order_id.order_items`,
//   {
//     method: 'POST',
//     headers: {
//       'Content-Type': 'application/vnd.api+json',
//       'Commerce-Cart-Token': `ABC-123`,
//       'Commerce-Current-Store': `98106e1f-ca58-42b1-a25f-8ac20c13847a`,
//     },
//     body: JSON.stringify({
//       data: [
//         {
//           type: 'product-variation--video',
//           id: '57af6be9-14a5-4267-858d-a86b7dc2cb58',
//           meta: {
//             quantity: 1,
//             combine: true,
//           },
//         },
//       ],
//     }),
//   }
// );
// const data = await res.json();
// console.log('LOG::  ~ data', data);

// const node = await getResource<DrupalNode>(
//   'node--article',
//   '5d5da489-ffb5-49c7-88b6-f147664bca4a'
// );

//     return {
//       props: { session },
//     };
//   } catch {
//     return {
//       props: {},
//     };
//   }
// };

export default Cart;
